GCCFLAGS = -fsanitize=address,undefined,signed-integer-overflow -o

up1:
gcc $(GCCFLAGS) solution up04-1.c && ./solution

up2:
gcc $(GCCFLAGS) solution up04-2.c && ./solution

up3:
gcc $(GCCFLAGS) solution up04-3.c && ./solution

up4:
gcc $(GCCFLAGS) solution up04-4.c && ./solution

up5:
gcc $(GCCFLAGS) solution up04-5.c && ./solution

clear:
rm solution