GCCFLAGS = -fsanitize=address,undefined,signed-integer-overflow -o

up1:
gcc $(GCCFLAGS) solution up01-1.c && ./solution

up2:
gcc $(GCCFLAGS) solution up01-2.c && ./solution

up3:
gcc $(GCCFLAGS) solution up01-3.c && ./solution

up4:
gcc $(GCCFLAGS) solution up01-4.c && ./solution

up5:
gcc $(GCCFLAGS) solution up01-5.c && ./solution

clear:
rm solution