GCCFLAGS = -fsanitize=address,undefined,signed-integer-overflow -o

up1:
	gcc $(GCCFLAGS) solution up07-1.c && ./solution

up2:
	gcc $(GCCFLAGS) solution up07-2.c && ./solution

up3:
	gcc $(GCCFLAGS) solution up07-3.c && ./solution

up4:
	gcc $(GCCFLAGS) solution up07-4.c && ./solution

up5:
	gcc $(GCCFLAGS) solution up07-5.c && ./solution

clear:
	rm solution
